# Generated by Django 2.2 on 2021-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_wish_granted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
