# Generated by Django 2.2 on 2021-06-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_pw',
            new_name='pw_confirm',
        ),
    ]
